env_name: CartPole-v1
model_path: ./models
model_name: vanilla_ppo
model_use_specs: true

cfg_specs:
  action_names: 
    push: "action"
  obs_names:
    x: "obs[0]"
    x_dot: "obs[1]"
    theta: "obs[2]"
    theta_dot: "obs[3]"  
  specs: cartpole.stl
    
  eval_formulas:
    phi_stable:

cfg_test: 
  init_seeds: 1
  num_ep: 10
  num_steps: 500 
  render_mode: 'human'

cfg_train:
  n_envs: 12  
  eval_freq: 10000
  
  algo:
    ppo:
      batch_size: 128
      neurons: 128
      learning_rate: 5e-4
      total_timesteps: 200_000
      tensorboard:
        tb_path: ./tb_logs
