env_name: CartPole-v1
model_path: ./models
model_name: vanilla_ppo

cfg_test: 
  init_seeds: 1
  num_ep: 5
  num_steps: 100 
  render: true

cfg_train:
  algo:
    ppo:
      batch_size: 128
      n_envs: 12
      neurons: 128
      learning_rate: 5e-4
      total_timesteps: 10_000
      tensorboard:
        tb_path: ./tb_logs
