cfg_test:
  init_seeds: 1
  num_ep: 5
  num_steps: 500
  render_mode: human
cfg_train:
  algo:
    ppo:
      batch_size: 256
      clip_range: 0.2
      ent_coef: 0.0
      gae_lambda: 0.8
      gamma: 0.98
      learning_rate: 5e-4
      neurons: 128
      tensorboard:
        tb_path: ./tb_logs
      total_timesteps: 250000
env_name: CartPole-v1
model_name: vanilla_ppo
model_path: ./models
