cfg_specs:
  action_names:
    push: action
  eval_formulas:
    phi_far_left: null
  obs_names:
    theta: obs[2]
    theta_dot: obs[3]
    x: obs[0]
    x_dot: obs[1]
  specs: 'signal push, x, x_dot, theta, theta_dot, reward



    go_left := x_dot[t]>0

    far_left := x[t]<-0.1

    phi_far_left := ev_[0, 100] far_left'
cfg_test:
  init_seeds: 1
  num_ep: 5
  num_steps: 500
  render: true
cfg_train:
  algo:
    ppo:
      batch_size: 128
      learning_rate: 1e-4
      n_envs: 12
      neurons: 128
      tensorboard:
        tb_path: ./tb_logs
      total_timesteps: 200000
env_name: CartPole-v1
model_name: vanilla_ppo
model_path: ./models
