#env_name: MiniGrid-Unlock-v0
env_name: MiniGrid-CustomUnlock-v1
model_path: ./models/grid_12
model_name: specs
import_module: unlock_custom
model_use_specs: True # Here we train without specs

cfg_specs:
  obs_names:
    ego: "obs[81]"
    obj_front: "obs[78]" 
    key_visible: "1 if any(i % 3 == 0 for i, val in enumerate(obs) if val == 5) else 0"
  action_names:
    action: "action"
  specs: minigrid.stl
  
  eval_formulas:
    find_key:
      t0: 0
      eval_all_steps: False
    find_key_and_door:
      t0: 0
      eval_all_steps: False
  # obs_formulas:
  #   key_is_visible:
  #     obs_name: 'obs_key_visible'
  #     past_horizon: 0  
  # end_formulas:
  #   drop_key:
  #     past_horizon: 0  
  #     eval_all_steps: True
  cfg_rm: cfg_rm.yml

cfg_train:
  total_timesteps: 1_000_000
  #n_envs: 1
  eval_freq: 15_000  
  
  algo:
    ppo:
      device: cpu    
      verbose: 1
      max_grad_norm: 0.5
      batch_size: 64
      clip_range: 0.2
      ent_coef: 0.01
      vf_coef: 0.5
      gae_lambda: 0.95
      gamma: 0.99
      learning_rate: 0.00025
      n_epochs: 4
      n_steps: 128
      policy: 'MlpPolicy'
      tensorboard_log: ./tb_logs/key_visible

cfg_test:
  init_seeds: 0
  num_ep: 2
  num_steps: 150
  render_mode: 'human'