#env_name: MiniGrid-Unlock-v0
env_name: MiniGrid-CustomUnlock-v1
model_path: ./models
model_name: model_step_200704
import_module: unlock_custom
model_use_specs: False # Here we train without specs

cfg_specs:
  obs_names:
    ego: "obs[81]"
    obj_front: "obs[78]"
  specs: minigrid.stl
  
  eval_formulas:
    find_key:
      t0: 0
      eval_all_steps: False
    find_key_and_door:
      t0: 0
      eval_all_steps: False

  cfg_rm: cfg_rm.yml

cfg_train:
  total_timesteps: 100_000
  n_envs: 1
  eval_freq: 15_000  
  

  algo:
    ppo:
      device: cpu    
      verbose: 1
      batch_size: 64
      clip_range: 0.2
      ent_coef: 0.0
      gae_lambda: 0.95
      gamma: 0.99
      learning_rate: 0.00025
      n_epochs: 10
      n_steps: 128
      policy: 'MlpPolicy'
      tensorboard_log: ./tb_logs

cfg_test:
  init_seeds: 0
  num_ep: 2
  num_steps: 100
  render_mode: 'human'