#env_name: MiniGrid-Unlock-v0
env_name: MiniGrid-CustomUnlock-v1
model_name: model
model_path: ./models

#cfg_env: cfg_env.yml
cfg_specs:
  obs_names:
    ego: "obs[81]"
  specs: minigrid.stl
  eval_formulas:
    phi_stable:
    

cfg_train:
 algo:
   ppo:
     batch_size: 128
     n_envs: 12
     neurons: 128
     learning_rate: 5e-4
     total_timesteps: 200_000
     tensorboard:
       tb_path: ./tb_logs


cfg_test:
  init_seeds: 0
  num_ep: 1
  num_steps: 100
  render: True