#env_name: MiniGrid-Unlock-v0
env_name: MiniGrid-CustomUnlock-v1

#cfg_env: cfg_env.yml
cfg_specs:
  obs_names:
    ego: "obs[81]"
    door: "obs[78]"
  specs: minigrid.stl
  
  eval_formulas:
    key:
      past_horizon: 0.
      eval_all_steps: True
    

cfg_train:
 algo:
  total_timesteps: 200_000
  n_envs: 8
  ppo:
    batch_size: 128
    learning_rate: !!float 5e-4
    tensorboard: ./tb_logs


cfg_test:
  init_seeds: 0
  num_ep: 1
  num_steps: 100
  render_mode: 'human'