#env_name: MiniGrid-Unlock-v0
env_name: MiniGrid-CustomUnlock-v1
model_path: ./models
model_name: vanilla_ppo
model_use_specs: True

cfg_specs:
  obs_names:
    ego: "obs[81]"
    obj_front: "obs[78]"
  specs: minigrid.stl
  
  eval_formulas:
    has_key:
      past_horizon: 0.
      eval_all_steps: True

  cfg_rm: cfg_rm.yml

cfg_train:
 algo:
  total_timesteps: 200_000
  n_envs: 8
  ppo:
    batch_size: 128
    learning_rate: !!float 5e-4
    tensorboard_log: ./tb_logs


cfg_test:
  init_seeds: 0
  num_ep: 1
  num_steps: 100
  render_mode: 'human'