env_name: highway-v0
import_module: highway
make_env_train: make_env_train
make_env_test: make_env_test
model_path: ./models
model_name: basic_with_obs
model_use_specs: True

cfg_env: cfg_env.yml
cfg_specs: cfg_specs_with_obs.yml
cfg_train: 
  algo:
    total_timesteps: 200_000
    n_envs: 12      
    ppo:  
      batch_size: 128      
      learning_rate: 5e-4    
      tensorboard_log: ./tb_logs    

cfg_test: 
  init_seeds: 0
  num_ep: 5
  num_steps: 100 
  render: true