#model_name: with_obs
model_name: test_dev
model_path: ./models
algo:
  ppo:  
    batch_size: 128
    n_envs: 12
    neurons: 128
    learning_rate: 5e-4    
    total_timesteps: 200_000
    tensorboard:
      tb_path: ./tb_logs    
