highway-env:
  policy: "MlpPolicy"
  n_envs: 12
  device: 'cpu'
  policy_kwargs: policy_kwargs
  n_steps: 64
  batch_size: 64
  n_epochs: 10
  learning_rate: 5e-4
  gamma: 0.9
  verbose: 1
  tensorboard_log: "./highway_ppo/"

